// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWz5A7drnNTbpCTweXTaI8oGXGR74tffQ',
    appId: '1:713014731932:web:ab37b7f9df3e91788eb959',
    messagingSenderId: '713014731932',
    projectId: 'ieee-isims-app',
    authDomain: 'ieee-isims-app.firebaseapp.com',
    storageBucket: 'ieee-isims-app.appspot.com',
    measurementId: 'G-M2P30CJ2YW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyzs_7WEk94Qee1F1xKpg1rkVmM2K83Os',
    appId: '1:713014731932:android:0d88a94ec9c12b2a8eb959',
    messagingSenderId: '713014731932',
    projectId: 'ieee-isims-app',
    storageBucket: 'ieee-isims-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmYjzcUynPoa7LOgtd35PpuEpcc5woKTI',
    appId: '1:713014731932:ios:478de6368b20d3f88eb959',
    messagingSenderId: '713014731932',
    projectId: 'ieee-isims-app',
    storageBucket: 'ieee-isims-app.appspot.com',
    iosBundleId: 'com.example.ieeeIsimsSb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmYjzcUynPoa7LOgtd35PpuEpcc5woKTI',
    appId: '1:713014731932:ios:478de6368b20d3f88eb959',
    messagingSenderId: '713014731932',
    projectId: 'ieee-isims-app',
    storageBucket: 'ieee-isims-app.appspot.com',
    iosBundleId: 'com.example.ieeeIsimsSb',
  );
}
